spring:
  application:
    name: sistema-ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_ecommerce?allowPublicKeyRetrieval=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
      connection-timeout: 5000
      maximum-pool-size: 5
      pool-name: pool-sistema_ecommerce
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


server:
  port: 8081
  servlet:
    context-path: /sistema-ecommerce